/*
 * ConfigGUI.java
 *
 * Contiene la definicion de la interface de usuario para la configuracion 
 * inicial del programa, permite establecer el tamaño de la memoria principal,
 * secundaria y le tamaño de la pagina
 * 
 */
package memsimu.GUI;

/**
 *
 * @author Ivan Arno y Ricardo Alustiza
 */
public class ConfigGUI extends javax.swing.JDialog {
    int memPrincipal;
    int memSecundaria;
    int tamPagina;
    
    public int getTamMemoriaPrincipal()
    {
        return memPrincipal;
    }

    public int getTamMemoriaSecundaria()
    {
        return memSecundaria;
    }

    public int getTamPagina()
    {
        return tamPagina;
    }

    /** Creates new form ConfigGUI */
    public ConfigGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        memPrincipal =  1 << 10; //1MB = 1024K
        memSecundaria = 1 << 14; //16MB = 16384K
        tamPagina= 4; // 4K
        jtMemoriaPrincipal.setText(Integer.toString(memPrincipal));
        jtMemoriaSecundaria.setText(Integer.toString(memSecundaria));
        jtTamPagina.setText(Long.toString(tamPagina));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtMemoriaPrincipal = new javax.swing.JTextField();
        jtMemoriaSecundaria = new javax.swing.JTextField();
        jtTamPagina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion del simulador");
        setModal(true);
        setResizable(false);

        jButton1.setText("Aceptar");
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño de memoria principal (KB):");

        jLabel2.setText("Tamaño de memoria secundaria (KB):");

        jLabel3.setText("Tamaño de pagina (KB):");

        jtMemoriaPrincipal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtMemoriaPrincipal.setText("0");
        jtMemoriaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMemoriaPrincipalActionPerformed(evt);
            }
        });

        jtMemoriaSecundaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtMemoriaSecundaria.setText("0");

        jtTamPagina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtTamPagina.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jtMemoriaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jtTamPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jtMemoriaSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMemoriaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMemoriaSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTamPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMemoriaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMemoriaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMemoriaPrincipalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        memPrincipal=Integer.parseInt(jtMemoriaPrincipal.getText());
        memSecundaria=Integer.parseInt(jtMemoriaSecundaria.getText());
        tamPagina=Integer.parseInt(jtTamPagina.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtMemoriaPrincipal;
    private javax.swing.JTextField jtMemoriaSecundaria;
    private javax.swing.JTextField jtTamPagina;
    // End of variables declaration//GEN-END:variables
}
